#!/usr/bin/env python

# converter from seurat .rds to cellbrowser format

import sys
from os.path import join, dirname

import sys
sys.path.insert(0,  join(dirname(__file__), "cbPyLib") )
from cellbrowser import seurat
seurat.cbImportSeuratCli()
