#!/usr/bin/env python

# converter from scanpy to cellbrowser format
# scanpy requires py3 but anndata runs on py2

import sys
from os.path import join, dirname

# tested with python 2.7 and python3, see cellbrowser.py
import sys
sys.path.insert(0,  join(dirname(__file__), "cbPyLib") )
from cellbrowser import convert
convert.cbImportScanpyCli()
