#!/usr/bin/env python

# converter from cellranger to cellbrowser format
# uses scanpy to parse hdf5, so that part works only on python3

import sys
from os.path import join, dirname

# tested with python 2.6 and python3, see cellbrowser.py
import sys
sys.path.insert(0,  join(dirname(__file__), "cbPyLib") )
from cellbrowser import convert
convert.cbCellrangerCli()
