#!/usr/bin/env python
import sys
from os.path import join, dirname

# tested with python 2.6 and python3, see cellbrowser.py
import sys
sys.path.insert(0,  join(dirname(__file__), "cbPyLib") )
from cellbrowser import geneinfo
geneinfo.cbMarkerAnnotateCli()
