#!/usr/bin/env python3
# scanpy exists only in python3, so this script works only in python3

# runs a single cell matrix through scanpy and output 
# everything as tab-sep files
from os.path import join, dirname
import sys
sys.path.insert(0,  join(dirname(__file__), "cbPyLib") )
from cellbrowser import cellbrowser

cellbrowser.cbScanpyCli()
