#!/usr/bin/env python

# runs an expression matrix through Seurat and outputs
# everything as tab-sep files
from os.path import join, dirname
import sys
sys.path.append( join(dirname(__file__), "cbPyLib") )
from cellbrowser import seurat

seurat.cbSeuratCli()
