#!/usr/bin/env python

# tested with python 2.6 and python3, see cellbrowser.py

import sys
from os.path import join, dirname

import sys
sys.path.append( join(dirname(__file__), "cbLib") )
import cellbrowser
cellbrowser.cbMake_cli()
