#!/usr/bin/env python

# tested with python 2.6 and python3, see cellbrowser.py

import sys
from os.path import join, dirname

import sys
sys.path.insert(0,  join(dirname(__file__), "cbPyLib") )
from cellbrowser import cellbrowser
cellbrowser.cbUpgradeCli()
